### ISSUE TITLE
Add libjpeg-dev and python-dev to dependencies

### ISSUE THREAD

**Issue by joereynolds** [maximinus/pygame-website#3]
My first time installing Django for this project was mostly painless but there were a few bumps that I happened to come across.

* libjpeg-dev is needed for the Pillow library
* python-dev is needed for the python.h headers that are used when building pillow

It might be safe to assume that people already have these, but I didn't. Just a heads up!

**Comment by maximinus** [comment]
Good catch. Pillow is always a bit of a pain, and literally it's only used to re-size user image uploads. I'll add to the documentation in a couple of days and close this issue afterwards.

**Comment by maximinus** [comment]
Added to readme file in root directory.
