### ISSUE TITLE
untrack binaries files

### ISSUE THREAD

**Issue by andarms** [maximinus/pygame-website#7]
We don't need track the binaries files like the db file and the media folder.

The db file changes many often and this changes causes Merge conflicts. this file can be create easily so we just need add to the readme the instructions of how to make the db's migrations and create and super user.

The media folder neither need be tracked this can be created automatically and gonna change when we create any new test user.

**Comment by maximinus** [comment]
Done. If I time today I'll write a small script to setup the DB with a few users, posts forums and the like.
